%% 图像增强(3)
%读取图片并转换为灰度图片
I=imread('lena.jpg');
imshow(I);
I1=rgb2gray(I);
imshow(I1);
%% 滤波器
Idouble=im2double(I1);
M=size(Idouble,1);
N=size(Idouble,2);
n=6;%滤波器的阶数
D0=80;%滤波器的截止频率
[u,v]=meshgrid(-M/2:(M/2-1),-N/2:(N/2-1));%产生离散数据
D=sqrt(u.^2+v.^2);
%各种不同的滤波器
H1=double(D<=D0);%理想低通滤波器
H2=1./(1+(D/D0).^(2*n));%Butterworth低通滤波器
H3=exp(-(D/D0).^n);%指数低通滤波器
H4=double(D>=D0);%理想高通滤波器
H5=1./(1+(D0./D).^(2*n));%Butterworth高通滤波器
H6=exp(-(D0./D).^n);%指数高通滤波器
%进行滤波
Ifft=fftshift(fft2(Idouble));%傅立叶变换和平移
K1=Ifft.*H1;
K2=Ifft.*H2;
K3=Ifft.*H3;
K4=Ifft.*H4;
K5=Ifft.*H5;
K6=Ifft.*H6;
%傅立叶反变换
I2=ifft2(ifftshift(K1));
figure,imshow(I2);
title('理想低通滤波器');
I3=ifft2(ifftshift(K2));
figure,imshow(I3);
title('Butterworth低通滤波器');
I4=ifft2(ifftshift(K3));
figure,imshow(I4);
title('指数低通滤波器');
I5=ifft2(ifftshift(K4));
figure,imshow(I5);
title('理想高通滤波器');
I6=ifft2(ifftshift(K5));
figure,imshow(I6);
title('Butterworth高通滤波器');
I7=ifft2(ifftshift(K6));
figure,imshow(I7);
title('指数高通滤波器');